### ISSUE TITLE
完善用户故事user-story.md文档，增加功能点验收标准

### ISSUE THREAD

**Issue by Darkone0** [OS-ABC/Kcoin-Golang#113]
#### 自行认领，先到先得，每人完善2-3个用户故事标准，如有剩余随机分配给只认领两个任务的同学
- [x] 1. 作为一个平台管理者，我希望登陆时能够识别我的管理员身份，以便于进行相应的管理操作
- [x] 2. 作为一个普通用户，我希望直接通过github、gitee登陆，以便于将账号与我的github相关联，进行导入项目、参与项目等操作
- [x] 3. 作为一个项目管理者，我希望通过项目url导入项目
- [x] 4. 作为一个项目管理者，我希望通过点击获取到的github仓库列表item，导入项目
- [x] 5. 作为一个项目管理者，我希望我在导入项目时，可以制定自己的初始贡献量评定规则
- [x] 6. 作为一个独裁制项目管理者，我希望我在导入项目后，可以更改贡献量评定规则
- [x] 7. 作为一个项目管理者，我希望可以设置项目封面，以便更好的展示给其他用户
- [x] 8. 我是一名想在开源项目中做贡献的用户，我希望Kcoin能展示项目在Github上的star和committer数量等信息，以便我判断一个项目是否活跃且值得加入。
- [x] 9. 作为一名投资者，我希望看到项目被哪些公司或机构使用，这样可以让我更好地决策，到底要不要给这个项目投资、要投资多少。
- [x] 10. 我是一名项目管理者，我希望查看项目总体CC（市值cs*股价）和项目公共CC
- [x] 11. 作为一个普通用户，我希望快速查看我参与的项目中我的CS和分配得到的CC
- [x] 12. 作为一名项目管理者，我想要关注贡献者列表与具体工作列表，以便于增强对项目掌控。
- [x] 13. 作为一个普通用户，我想要查看目前项目所有成员的CS排行榜
- [x] 14. 作为一个普通用户，我想要查看目前项目所有动态，包括项目规则的变化和公共CC变化
- [x] 15. 作为一个普通用户，我想要查看目前项目的贡献度评定规则，以便了解游戏规则
- [x] 16. 作为一个普通用户，我希望我所在的项目在被管理员导入后，接收到邮件通知，提醒我加入kcoin平台，以便获取CS
- [x] 17. 作为一个普通用户，我在给一个已托管的项目贡献成为一个新contributor时，希望收到邮件通知提醒我加入kcoin平台，以便获取CS
- [x] 18. 作为一个普通用户，我希望收到我参与的项目动态消息，包括项目规则的变化、决议投票和公共CC变化等，以便及时了解情况。
- [x] 19. 我是一名普通用户，我希望通过向开源社区提交代码，按照该项目贡献度规则获得相应的贡献度和CS
- [x] 20. 我是kcoin基金会，我希望用CC按股价比例收购某个项目的CS，以便支持项目发展
- [x] 21. 我是一名投资者，我希望用法币向基金会购买CC，以便于收购某个项目的股权、投资项目。
- [x] 22. 我是一名投资者，我希望用CC按股价比例收购某个项目的CS，这些CS由全体成员按比例缴出，以便获得该项目的CS，进而控制投票权
- [x] 23. 我是一名投资者，我希望用CC按股价比例向某个项目成员购买他手中的CS，从而拥有项目的投票权

**Comment by zhang2j** [comment]
let me fix 1, 2, 3

**Comment by jiangyuzhao** [comment]
let me fix 5, 7

**Comment by msq0313** [comment]
let me fix 15, 16

**Comment by secrettttt** [comment]
let me fix 13,14

**Comment by scarydemon2** [comment]
let me fix 8.9

**Comment by secrettttt** [comment]
let me fix 11,13,14

**Comment by TMZup** [comment]
let me fix 4, 10

**Comment by Fanwh325** [comment]
let me fix 17,18,19

**Comment by Darkone0** [comment]
let me fix 6,12
