### ISSUE TITLE
修复使用GitHub登录时的一个BUG。

### ISSUE THREAD

**Issue by Fanwh325** [OS-ABC/Kcoin-Golang#118]
现在每次使用GitHub登录的时候，都会在K_User表中插入一条用户信息，同一个人多次登录，会出现重复的多条信息。正确的情况应该是先判断是否该用户是否已经注册，如果注册过，不插入，未注册才插入。

**Comment by fangzfang** [comment]
let me fix/implement

**Comment by fangzfang** [comment]
已经修复，#124
