### ISSUE TITLE
检查一个github仓库地址是否合法

### ISSUE THREAD

**Issue by jiangyuzhao** [OS-ABC/Kcoin-Golang#131]
函数名：CheckGithubRepoUrl
参数：gitUserId string, url string
返回值 ErrorCode error
该函数Url是否合法，以及检查当前用户是否有权限访问该仓库。
该函数首字母大写！

**Comment by PHP-is-Best** [comment]
let me fix

**Comment by jiangyuzhao** [comment]
我更新了一下参数声明~这里用gitUserId做参数，自2019.12.1更新后，所有对github用户的标识均通过GithubId标识，即通过github OAuth返回的用户信息中的id标识。
