### ISSUE TITLE
首页增加“平台管理”入口，并实现平台管理页面公共部分

### ISSUE THREAD

**Issue by zhang2j** [OS-ABC/Kcoin-Golang#138]
1. 当一个身份是平台管理员的用户登录的时候，在首页显示平台管理链接，点击后进入平台管理页面。
2. 平台管理页面分平台信息、注资管理、项目注资三个页面，实现这三个页面公共的部分（导航栏）。

**Comment by secrettttt** [comment]
let me fix !
