### ISSUE TITLE
导入项目页面和个人项目页面完善

### ISSUE THREAD

**Issue by zhang2j** [OS-ABC/Kcoin-Golang#143]
1. 导入项目时，当用户输入url后可以在导入项目页面显示url对应的项目名称。
2. 通过点击个人项目列表导入项目时，能获取点击事件对应的url。
2. 将personalPage页面中变为“我参加的项目/我管理的项目”两栏，并且导入项目后跳转到该页面。

**Comment by anaana35** [comment]
let me fix this issue
