### ISSUE TITLE
增加项目描述textfield，保存项目相关信息到session中

### ISSUE THREAD

**Issue by zhang2j** [OS-ABC/Kcoin-Golang#182]
1. 在导入项目时增加项目描述textfield，允许输入二百字以内的项目描述，同时在项目设置页面添加修改该项目描述的textfield。
2. 每次取项目相关信息（cc、cs、star数量、项目描述等等）时，都先查询session中是否有相关数据，有就直接从session中取，如果没有就存进去。

**Comment by anaana35** [comment]
let me fix it
