### ISSUE TITLE
为我的项目中的项目添加到项目详情的跳转，在添加项目时加入js验证

### ISSUE THREAD

**Issue by zhang2j** [OS-ABC/Kcoin-Golang#184]
1. 在个人页面的我的项目中为项目添加到项目详情的跳转，可以参考首页上项目的跳转实现。
2. 在添加项目时使用js验证该用户是否有权限导入该项目。当该仓库属于该用户或者属于该用户所属于的组织，那该用户就有权限导入这个仓库。

**Comment by Guibeen** [comment]
let me fix it

**Comment by Guibeen** [comment]
第2点需要有具体的效果吗？有权限、无权限时，要分别显示些什么吗

**Comment by Guibeen** [comment]
第1点已完成。明确第二点：用户在step1输入url并点击下一步时，判断是否有权限，若有权限则正常进入下一步，否则不进入下一步，显示没有权限。

**Comment by Guibeen** [comment]
仓库属于该用户：判断url中的用户名。
用户属于该组织：判断url的组织，再看用户在不在组织内。（暂时设为false）
