### ISSUE TITLE
个人中心-余额：get

### ISSUE THREAD

**Issue by Darkone0** [OS-ABC/Kcoin-Golang#231]
查询数据库，得到个人CC余额，展示在个人中心-余额模块

**Comment by a5759567** [comment]
let me fix this

**Comment by chenseifer** [comment]
数据库开发已完成，K_User表格中，User_cc字段

**Comment by chenseifer** [comment]
数据库，K_User需删除现有触发器，
考虑到现有业务，User_cc 由购买、投资、分配、捐赠，由该四项业务进行触发器

**Comment by Guibeen** [comment]
let me try this issue.

**Comment by Darkone0** [comment]
personalPage：38行报错 : jsonBuf2, _ := models.GetPersonalRemainingCc(userName) 
userName未定义，已修改
sql语句有问题，没办法正常查询

**Comment by Guibeen** [comment]
已解决查询问题
