### ISSUE TITLE
webhooks处理逻辑

### ISSUE THREAD

**Issue by jiangyuzhao** [OS-ABC/Kcoin-Golang#258]
参考https://www.jianshu.com/p/f5965345a802实现即可。

首先需要检查一下secret，即这是不是一个合法post，函数实现为checkWebhookPostValid，接受request本身，返回bool值即可。
之后需要确认post到过来的数据是什么，是一个merge消息的话，就需要根据merge/push信息（这个合入的是谁）返回merge的user string和reviewers []string，以及关联的issue号。
需要一个函数处理issue，通过输入issue号获取相应信息。
如果post的消息是其他消息，比如issue新增的消息...这个浩哥来讲讲，方便讨论。本周实现的应该就这4个函数：检查合法，判断消息类型，merge消息的处理，issue信息的获取。其中判断消息类型和issue信息获取可以由一人完成。

**Comment by jiangyuzhao** [comment]
@scarydemon2 @Darkone0

**Comment by scarydemon2** [comment]
上面那个链接失效了

**Comment by scarydemon2** [comment]
刚之

**Comment by jiangyuzhao** [comment]
> 刚之

太过靠谱，你是打算做着4个函数中的哪些呢？

**Comment by jiangyuzhao** [comment]
> 刚之

都做不亏

**Comment by scarydemon2** [comment]
一个一个写呗。能写多少那就是天意
