### ISSUE TITLE
登陆界面跳转逻辑问题

### ISSUE THREAD

**Issue by Darkone0** [OS-ABC/Kcoin-Golang#96]
目前登陆后的跳转逻辑是：直接跳到主页homepage。
这是不合理的。
举个例子，访问个人中心页面需要登陆验证。当验证完成后应当执行之前的访问意图直接跳转到个人中心，然而现在的跳转逻辑是直接跳到主页。
一种思路：保留跳转意图，验证后重定向到意图页面

**Comment by scarydemon2** [comment]
let me fix it
